---
project: Field Demo
kind: PIPELINE
name: k8s-create-secret
icon: organization,left, is-ultramarine
enabled: true
concurrency: 10
input:
  secret_name: ''
  secret_data_token: ''
_inputMeta:
  secret_name:
    mandatory: true
    description: Name of secret
  secret_data_token:
    mandatory: true
    description: Token data to be added to secret
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Create Secret
stages:
  Create Secret:
    taskOrder:
    - Create secret
    tasks:
      Create secret:
        type: K8S
        endpoints:
          kubernetesServer: deanl-cluster
        input:
          action: APPLY
          timeout: 5
          filePath: ''
          scmConstants: {
            }
          yaml: |-
            apiVersion: v1
            kind: Secret
            metadata:
              name: '${input.secret_name}'
              namespace: default
            data:
              token: '${input.secret_data_token}'
